(deftheme system-type-darwin
  "Created 2016-01-05.")

(custom-theme-set-faces
 'system-type-darwin
 '(default ((t (:family "Source Code Pro" :foundry "nil" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#282828" :background "#f8fced" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#f8fced" :background "#282828"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#98ece8"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#282828"))))
 '(highlight ((t (:background "#e8eb98"))))
 '(region ((t (:foreground "#282828" :background "#e8eb98"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#e8fce8"))))
 '(trailing-whitespace ((t (:background "#f8e8e8"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#282828"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#40883f"))))
 '(font-lock-comment-face ((t (:foreground "#40883f"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "#989848"))))
 '(font-lock-doc-face ((t (:foreground "#40883f"))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#282828"))))
 '(font-lock-keyword-face ((t (:foreground "#989848"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#b85c57"))))
 '(font-lock-preprocessor-face ((t (:weight bold :foreground "#40883f"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#b85c57"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#b85c57"))))
 '(font-lock-string-face ((t (:foreground "#b85c57"))))
 '(font-lock-type-face ((t (:weight bold :foreground "#0287c8"))))
 '(font-lock-variable-name-face ((t (:foreground "#4fa8a8"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#b85c57"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#0287c8"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#8888c8"))))
 '(fringe ((t (:foreground "#40883f" :background "#e8fce8"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#8888c8" :background "#e7fcf7"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#282828" :background "#98ece8"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#b85c57"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color nil :style pressed-button) :foreground "#4d4d4d" :background "#4fa8a8"))))
 '(isearch ((t (:weight bold :foreground "#282828" :background "#98ece8"))))
 '(isearch-fail ((t (:weight bold :foreground "#282828" :background "#b85c57"))))
 '(lazy-highlight ((t (:weight bold :foreground "#282828" :background "#4fa8a8"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'system-type-darwin)
