(require 'go-mode)
(require 'go-oracle)
(require 'company-go)
(require 'go-eldoc)
(require 'go-projectile)

(add-to-list 'go-mode-hook (lambda ()
                             (setq-local tab-width 4)
                             (whitespace-mode 0)
                             (local-set-key (kbd "C-c C-r") 'go-remove-unused-imports)
                             (local-set-key (kbd "C-c C-k") 'godoc)))
(add-hook 'go-mode-hook #'go-eldoc-setup)
(add-hook 'before-save-hook #'gofmt-before-save)

(add-to-list 'exec-path "/usr/local/go/bin")
(setenv "PATH" (concat (getenv "PATH") ":" "/usr/local/go/bin"))
(setenv "GOPATH" "/Users/ghughes/lib/go:/Users/ghughes/wd/git-work/lib/go")
