(require 'dired-x)
(require 'sgml-mode)
(require 'info-look)
(require 'pretty-mode)
(global-pretty-mode 1)
(require 'uniquify)
(require 'zap-up-to-char)
(require 'mac-local)
(require 'popwin)
(popwin-mode 1)
(global-git-gutter+-mode 1)

(dired-x-bind-find-file)
