(require 'ggtags)

(define-key me-minor-mode-map [f2] 'jw-visit-source)
(define-key me-minor-mode-map [f3] 'flymake-display-err-menu-for-current-line)
(define-key me-minor-mode-map [f4] 'flymake-goto-next-error)
(define-key me-minor-mode-map "\C-a" 'mwim-beginning-of-code-or-line)
(define-key me-minor-mode-map "\C-e" 'mwim-end-of-code-or-line)
(define-key me-minor-mode-map "\C-ca" 'eshell)
(define-key me-minor-mode-map "\C-cA" 'org-agenda)
(define-key me-minor-mode-map "\C-cb" 'org-iswitchb)
(define-key me-minor-mode-map "\C-cB" 'speedbar-get-focus)
(define-key me-minor-mode-map "\C-cc" 'org-capture)
(define-key me-minor-mode-map "\C-cf" 'ffap)
(define-key me-minor-mode-map "\C-cF" 'ido-find-file-in-tag-files)
(define-key me-minor-mode-map "\C-cj" 'avy-goto-word-or-subword-1)
(define-key me-minor-mode-map "\C-ck" 'delete-pair)
(define-key me-minor-mode-map "\C-cl" 'org-store-link)
(define-key me-minor-mode-map "\C-cx" 'org-agenda)
(define-key me-minor-mode-map "\C-cm" 'woman)
(define-key me-minor-mode-map "\C-cn" 'tempo-forward-mark)
(define-key me-minor-mode-map "\C-co" 'ff-find-other-file)
(define-key me-minor-mode-map "\C-cp" 'tempo-backward-mark)
(define-key me-minor-mode-map "\C-cr" 'org-capture)
(define-key me-minor-mode-map "\C-cs" 'magit-status)
(define-key me-minor-mode-map "\C-ct" 'sane-term)
(define-key me-minor-mode-map "\C-cT" 'sane-term-create)
(define-key me-minor-mode-map "\C-cu" 'browse-url-at-point)
(define-key me-minor-mode-map "\C-cz" 'ace-jump-buffer)
(define-key me-minor-mode-map "\C-\M-z" 'zap-up-to-char)
(define-key me-minor-mode-map "\C-\M-y" 'kill-ring-search)
(define-key me-minor-mode-map (kbd "C-S-c C-S-c") 'mc/edit-lines)
(define-key me-minor-mode-map (kbd "C-'") 'er/expand-region)
(define-key me-minor-mode-map (kbd "C->") 'mc/mark-next-like-this)
(define-key me-minor-mode-map (kbd "C-<") 'mc/mark-previous-like-this)
(define-key me-minor-mode-map (kbd "C-c C-<") 'mc/mark-all-like-this)
(define-key me-minor-mode-map "\C-cit" 'unicode-character-shortcut-insert)
(define-key me-minor-mode-map "\C-ciu" 'unicode-character-insert)
(define-key me-minor-mode-map "\C-cii" 'iso8879-character-insert)
(define-key me-minor-mode-map "\C-ci'" 'unicode-smart-single-quote)
(define-key me-minor-mode-map "\C-ci\"" 'unicode-smart-double-quote)
(define-key me-minor-mode-map (kbd "M-x") 'helm-M-x)
(define-key me-minor-mode-map (kbd "M-y") 'helm-show-kill-ring)
(define-key me-minor-mode-map (kbd "C-x b") 'helm-mini)
(define-key me-minor-mode-map (kbd "C-c M-x") 'execute-extended-command)
(define-key me-minor-mode-map (kbd "M-+") 'e2wm:start-management)
(define-key me-minor-mode-map (kbd "C-z") popwin:keymap)
(define-key me-minor-mode-map (kbd "M-p") 'ace-window)
(define-key me-minor-mode-map (kbd "C-x C-f") 'helm-find-files)
(define-key me-minor-mode-map (kbd "C-c h o") 'helm-occur)
(define-key me-minor-mode-map (kbd "C-h SPC") 'helm-all-mark-rings)
(define-key me-minor-mode-map (kbd "M-9") 'corral-parentheses-backward)
(define-key me-minor-mode-map (kbd "M-0") 'corral-parentheses-forward)
(define-key me-minor-mode-map (kbd "M-[") 'corral-brackets-backward)
(define-key me-minor-mode-map (kbd "M-]") 'corral-brackets-forward)
(define-key me-minor-mode-map (kbd "M-\"") 'corral-double-quotes-backward)
(define-key me-minor-mode-map (kbd "C-c <down>") 'elwm-shift-down)
(define-key me-minor-mode-map (kbd "C-c <up>") 'elwm-shift-up)
(define-key me-minor-mode-map (kbd "C-c <left>") 'elwm-shift-left)
(define-key me-minor-mode-map (kbd "C-c <right>") 'elwm-shift-right)
(define-key me-minor-mode-map (kbd "C-c <next>") 'elwm-swap-down)
(define-key me-minor-mode-map (kbd "C-c <prior>") 'elwm-swap-up)
(define-key me-minor-mode-map (kbd "C-c w 2") 'elwm-split-window)


(add-hook 'python-mode-hook
          (lambda ()
            (local-set-key "\C-cNa" 'nosetests-all)
            (local-set-key "\C-cNm" 'nosetests-module)
            (local-set-key "\C-cN." 'nosetests-one)
            (local-set-key "\C-c\C-c" 'nosetests-again)
            (local-set-key "\C-cNpa" 'nosetests-pdb-all)
            (local-set-key "\C-cNpm" 'nosetests-pdb-module)
            (local-set-key "\C-cNp." 'nosetests-pdb-one)))

(add-hook 'paredit-mode-hook
          (lambda ()
            (define-key paredit-mode-map (kbd "<prior>") 'paredit-forward-slurp-sexp)
            (define-key paredit-mode-map (kbd "<next>") 'paredit-backward-slurp-sexp)
            (define-key paredit-mode-map (kbd "<home>") 'paredit-backward-barf-sexp)
            (define-key paredit-mode-map (kbd "<end>") 'paredit-forward-barf-sexp)))


(define-key ggtags-mode-map (kbd "C-c g s") 'ggtags-find-other-symbol)
(define-key ggtags-mode-map (kbd "C-c g h") 'ggtags-view-tag-history)
(define-key ggtags-mode-map (kbd "C-c g r") 'ggtags-find-reference)
(define-key ggtags-mode-map (kbd "C-c g f") 'ggtags-find-file)
(define-key ggtags-mode-map (kbd "C-c g c") 'ggtags-create-tags)
(define-key ggtags-mode-map (kbd "C-c g u") 'ggtags-update-tags)

(define-key ggtags-mode-map (kbd "M-,") 'pop-tag-mark)

(define-key prog-mode-map (kbd "M-RET") 'emr-show-refactor-menu)
